---
- hosts: all

  pre_tasks:
    - name: Update apt cache and upgrade
      apt: pkg=dirmngr update_cache=yes
      become: yes

    - name: Install ntpdate for time synchronisation
      apt: pkg=ntpdate
      become: yes

    - name: Install unzip
      apt: pkg=unzip
      become: yes

    - name: Install time
      apt: pkg=time
      become: yes

  roles:
    - python
    - pipx
    - slowhttptest
    - wapiti
    - dnsmap
    - dnsrecon
    - nmap
    - ncrack
    - hping3
    - apache-bench
    - dig
    - mz
    - mitmproxy
    - theharvester
    - semgrep
    - browsh
