---
- hosts: all

  pre_tasks:
    - name: Update apt cache and upgrade
      apt: pkg=dirmngr update_cache=yes
      become: yes

    - name: Add the repository key for stretch backports repository
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 648ACFD622F3D138
      become: yes

    - name: Install avahi for MDNS
      apt: pkg=avahi-daemon
      become: yes

    - name: Install avahi-utils for working with MDNS
      apt: pkg=avahi-utils
      become: yes

    - name: Install ntpdate for time synchronisation
      apt: pkg=ntpdate
      become: yes

    - name: Install unzip
      apt: pkg=unzip
      become: yes

    - name: Install time
      apt: pkg=time
      become: yes

    - name: Install lynx command line web browser
      apt: pkg=lynx
      become: yes

  roles:
    - python
    - pipx
    - htcap
    - slowhttptest
    - wapiti
    - dnsmap
    - dnsrecon
    - nmap
    - ncrack
    - hping3
    - apache-bench
    - dig
    - mz
    - mitmproxy
    - theharvester
    - semgrep
