---
- name: Setup Victim Services
  hosts: all

  pre_tasks:
    - name: Update apt cache and upgrade
      ansible.builtin.apt:
        pkg: dirmngr
        update_cache: true
      become: true

    - name: Install ntpdate for time synchronisation
      ansible.builtin.apt:
        name: ntpdate
        state: present
      become: true

    - name: Install htop for process monitoring
      ansible.builtin.apt:
        name: htop
        state: present
      become: true

    - name: Install smem for memory monitoring
      ansible.builtin.apt:
        name: smem
        state: present
      become: true

    - name: Install iftop for network monitoring
      ansible.builtin.apt:
        name: iftop
        state: present
      become: true

    - name: Install iotop for disk I/O monitoring
      ansible.builtin.apt:
        name: iotop
        state: present
      become: true

    - name: Install nmon for general system performance monitoring
      ansible.builtin.apt:
        name: nmon
        state: present
      become: true

    - name: Install time
      ansible.builtin.apt:
        name: time
        state: present
      become: true

  roles:
    - python
    - docker
    - dig
    - browsh

  post_tasks:
    - name: Add vagrant user to user groups
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true
      become: true
