---
- name: Setup Security Testing Tools
  hosts: all

  pre_tasks:
    - name: Update apt cache and upgrade
      ansible.builtin.apt:
        pkg: dirmngr
        update_cache: true
      become: true

    - name: Install ntpdate for time synchronisation
      ansible.builtin.apt:
        name: ntpdate
        state: present
      become: true

    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
      become: true

    - name: Install time
      ansible.builtin.apt:
        name: time
        state: present
      become: true

  roles:
    - python
    - pipx
    - slowhttptest
    - wapiti
    - dnsmap
    - dnsrecon
    - nmap
    - ncrack
    - hping3
    - apache-bench
    - dig
    - mz
    - mitmproxy
    - spiderfoot
    - semgrep
    - browsh
    - zap
