---
- name: Setup Victim Services
  hosts: all

  pre_tasks:
    - name: Update apt cache and upgrade
      ansible.builtin.apt:
        pkg: dirmngr
        update_cache: true
      become: true

    - name: Install ntpdate for time synchronisation
      ansible.builtin.apt:
        name: ntpdate
        state: present
      become: true

    - name: Install htop for process monitoring
      ansible.builtin.apt:
        name: htop
        state: present
      become: true

    - name: Install smem for memory monitoring
      ansible.builtin.apt:
        name: smem
        state: present
      become: true

    - name: Install iftop for network monitoring
      ansible.builtin.apt:
        name: iftop
        state: present
      become: true

    - name: Install iotop for disk I/O monitoring
      ansible.builtin.apt:
        name: iotop
        state: present
      become: true

    - name: Install nmon for general system performance monitoring
      ansible.builtin.apt:
        name: nmon
        state: present
      become: true

    - name: Install time
      ansible.builtin.apt:
        name: time
        state: present
      become: true

  roles:
    - python
    - docker
    - dig
    - browsh

  post_tasks:
    - name: Add vagrant user to user groups
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true
      become: true

    - name: Dnsmasq
      community.docker.docker_container:
        name: security-testing-dnsmasq
        image: dockurr/dnsmasq
        networks:
          - name: vagrant_network_10.6.6.0/24
            ipv4_address: 10.6.6.8
        volumes:
          - "{{ pwd }}/dnsmasq.conf:/etc/dnsmasq.conf"
        restart_policy: always
      become: true

    - name: Juice Shop
      community.docker.docker_container:
        name: security-testing-juice-shop
        image: bkimminich/juice-shop
        networks:
          - name: vagrant_network_10.6.6.0/24
            ipv4_address: 10.6.6.9
        ports:
          - "3000:3000"
        memory: "256m"
        cpu_shares: 50
        ulimits:
          - nofile:1024:2048
        restart_policy: always
      become: true

    - name: Webgoat
      community.docker.docker_container:
        name: security-testing-webgoat
        image: webgoat/webgoat
        networks:
          - name: vagrant_network_10.6.6.0/24
            ipv4_address: 10.6.6.10
        ports:
          - 3001:8080
        restart_policy: always
      become: true

    - name: Hackazon
      community.docker.docker_container:
        name: security-testing-hackazon
        image: ianwijaya/hackazon
        networks:
          - name: vagrant_network_10.6.6.0/24
            ipv4_address: 10.6.6.11
        ports:
          - 3002:80
          - 3003:443
        restart_policy: always
      become: true
