---
- hosts: all

  pre_tasks:
    - name: Update apt cache and upgrade
      apt: pkg=dirmngr update_cache=yes
      become: yes

    - name: Install ntpdate for time synchronisation
      apt: pkg=ntpdate
      become: yes

    - name: Install htop for process monitoring
      apt: pkg=htop
      become: yes

    - name: Install smem for memory monitoring
      apt: pkg=smem
      become: yes

    - name: Install iftop for network monitoring
      apt: pkg=iftop
      become: yes

    - name: Install iotop for disk I/O monitoring
      apt: pkg=iotop
      become: yes

    - name: Install nmon for general system performance monitoring
      apt: pkg=nmon
      become: yes

  roles:
    - python
    - docker

  post_tasks:
    - name: Add vagrant user to user groups
      user: name=vagrant groups=docker append=yes
      become: yes

    - name: dnsmasq
      docker_container:
        name: security-testing-dnsmasq
        image: dockurr/dnsmasq
        networks:
          - name: vagrant_network_10.6.6.0/24
            ipv4_address: 10.6.6.8
        volumes:
          - "{{ pwd }}/dnsmasq.conf:/etc/dnsmasq.conf"
        restart_policy: always
      become: yes

    - name: Juice Shop
      docker_container:
        name: security-testing-juice-shop
        image: bkimminich/juice-shop
        networks:
          - name: vagrant_network_10.6.6.0/24
            ipv4_address: 10.6.6.9
        ports:
          - 3000:3000
        restart_policy: always
      become: yes

    - name: webgoat
      docker_container:
        name: security-testing-webgoat
        image: webgoat/webgoat
        networks:
          - name: vagrant_network_10.6.6.0/24
            ipv4_address: 10.6.6.10
        ports:
          - 3001:8080
        restart_policy: always
      become: yes

    - name: hackazon
      docker_container:
        name: security-testing-hackazon
        image: ianwijaya/hackazon
        networks:
          - name: vagrant_network_10.6.6.0/24
            ipv4_address: 10.6.6.11
        ports:
          - 3002:80
          - 3003:443
        restart_policy: always
      become: yes
