- name: Get nodejs setup script
  get_url: url=https://deb.nodesource.com/setup_13.x dest=/vagrant/nodejs-installer checksum="sha256:13b8764f37191334d4b1f264091abc3858f2051f5a292447eaf76cac5fe56076"
  become: yes

- name: Setup nodejs
  command: /bin/bash /vagrant/nodejs-installer
  become: yes

- name: Install nodejs
  apt: pkg=nodejs
  become: yes

- name: Install git
  apt: pkg=git-core
  become: yes

- name: Install htcap for single page application crawling
  git: repo=https://github.com/fcavallarin/htcap.git dest=/usr/lib/htcap
  become: yes

- name: Change file ownership, group and permissions
  file:
    path: /usr/lib/htcap
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant
  become: yes

- name: Add htcap to bin directory
  file:
    src: /usr/lib/htcap/htcap.py
    dest: /usr/bin/htcap
    state: link
  become: yes
