- name: Get nodejs
  get_url: url=https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz dest=/vagrant/node-v12.16.1-linux-x64.tar.xz checksum="sha256:b826753f14df9771609ffb8e7d2cc4cb395247cb704cf0cea0f04132d9cf3505"
  become: yes

- name: Move nodejs into lib directory
  unarchive:
    src: /vagrant/node-v12.16.1-linux-x64.tar.xz
    dest: /usr/lib
    remote_src: yes
  become: yes

- name: Add nodejs bin dir to system-wide $PATH
  copy:
    dest: /etc/profile.d/nodejs.sh
    content: 'PATH=$PATH:/usr/lib/node-v12.16.1-linux-x64/bin/'
  become: yes

- name: Install git
  apt: pkg=git-core
  become: yes

- name: Install htcap for single page application crawling
  git: repo=https://github.com/fcavallarin/htcap.git dest=/usr/lib/htcap
  become: yes

- name: Change file ownership, group and permissions
  file:
    path: /usr/lib/htcap
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant
  become: yes

- name: Add htcap to bin directory
  file:
    src: /usr/lib/htcap/htcap.py
    dest: /usr/bin/htcap
    state: link
  become: yes
