- name: Download arachni
  get_url:
    url: https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
    dest: /usr/lib/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
  become: yes

- name: Move arachni into lib directory
  unarchive:
    src: /usr/lib/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
    dest: /usr/lib
    remote_src: yes
  become: yes
