- name: Download arachni for Web Application Security Scanning
  get_url:
    url: https://downloads.arachni-scanner.com/nightlies/arachni-2.0dev-1.0dev-linux-x86_64.tar.gz
    dest: /vagrant/arachni-2.0dev-1.0dev-linux-x86_64.tar.gz
    checksum: sha256:ac366356f9d9864176b30190a3b9e5bee7cdfe0ba18f3938b06eaf48008b0f7d
  become: yes

- name: Move arachni into lib directory
  unarchive:
    src: /vagrant/arachni-2.0dev-1.0dev-linux-x86_64.tar.gz
    dest: /usr/lib
    remote_src: yes
  become: yes

- name: Change owner of system directory
  file: path=/usr/lib/arachni-2.0dev-1.0dev/system owner=vagrant group=vagrant recurse=yes
  become: yes

- name: Add arachni bin dir to system-wide $PATH
  copy:
    dest: /etc/profile.d/arachni.sh
    content: 'PATH=$PATH:/usr/lib/arachni-2.0dev-1.0dev/bin/'
  become: yes
