- name: Download arachni
  get_url:
    url: https://downloads.arachni-scanner.com/nightlies/arachni-2.0dev-1.0dev-linux-x86_64.tar.gz
    dest: /usr/lib/arachni-2.0dev-1.0dev-linux-x86_64.tar.gz
  become: yes

- name: Move arachni into lib directory
  unarchive:
    src: /usr/lib/arachni-2.0dev-1.0dev-linux-x86_64.tar.gz
    dest: /usr/lib
    remote_src: yes
  become: yes
