- name: Get theHarvester for e-mails, subdomains and names harvesting
  get_url: url=https://github.com/laramies/theHarvester/archive/master.zip dest=/vagrant/theHarvester-master.zip
  become: yes

- name: Unarchive
  unarchive:
    src: /vagrant/theHarvester-master.zip
    dest: /etc
    remote_src: yes
  become: yes

- name: Change file ownership, group and permissions
  file:
    path: /etc/theHarvester-master
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant
  become: yes

- name: Link /etc/theHarvester-master as /etc/theHarvester
  file:
    src: /etc/theHarvester-master
    dest: /etc/theHarvester
    state: link
  become: yes

- name: Add theHarvester to bin directory
  file:
    src: /etc/theHarvester/theHarvester.py
    dest: /usr/bin/theHarvester
    state: link
  become: yes

- name: Install required python modules
  pip: requirements=/etc/theHarvester-master/requirements/base.txt executable=/usr/lib/pyenv/shims/pip3.8
