- name: Install required packages
  apt: name={{ item }} update_cache=yes
  become: yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl

- name: Add docker apt key
  apt_key: url=https://download.docker.com/linux/debian/gpg
  become: yes

- name: Install docker apt repository
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable' state=present
  become: yes

- name: Install docker
  apt: name=docker-ce update_cache=yes
  become: yes
