---
- hosts: all

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes
      become: yes

    - name: Install avahi for MDNS
      apt: pkg=avahi-daemon
      become: yes

    - name: Install ntpdate for time synchronisation
      apt: pkg=ntpdate
      become: yes

    - name: Install pip
      apt: pkg=python-pip
      become: yes

    - name: Install docker-py
      pip: name=docker-py
      become: yes

  roles:
    - docker

  post_tasks:
    - name: Add vagrant user to user groups
      user: name=vagrant groups=docker append=yes
      become: yes

    - name: Create dnsmasq configuration
      copy:
        dest: /opt/dnsmasq.conf
        content: |
          log-queries
          no-resolv
          server=1.0.0.1
          server=1.1.1.1
          strict-order
          server=/security.com/10.6.6.7
          address=/tooling.security.com/10.6.6.6
          address=/victim.security.com/10.6.6.7
          address=/admin.security.com/10.6.6.7
      become: yes

    - name: dnsmasq
      docker_container:
        name: dnsmasq
        image: jpillora/dnsmasq
        network_mode: host
        env:
          HTTP_USER: "admin"
          HTTP_PASS: "admin123"
        volumes:
          - /opt/dnsmasq.conf:/etc/dnsmasq.conf
        restart_policy: always
      become: yes

    - name: Juice Shop
      docker_container:
        name: juice-shop
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
        restart_policy: always
      become: yes

    - name: webgoat
      docker_container:
        name: webgoat
        image: webgoat/webgoat-7.1
        ports:
          - 3001:8080
        restart_policy: always
      become: yes

    - name: hackazon
      docker_container:
        name: hackazon
        image: ianwijaya/hackazon
        ports:
          - 3002:80
          - 3003:443
        restart_policy: always
      become: yes

    - name: Setup DNS nameserver
      lineinfile: path=/etc/resolv.conf line="nameserver 10.6.6.7" regex="nameserver.*"
      become: yes

    - name: Add resolv.conf update to .bashrc
      lineinfile: dest=~/.bashrc line="sudo sed -i 's/nameserver.*/nameserver 10.6.6.7/g' /etc/resolv.conf"
