---
- hosts: all

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes
      become: yes

    - name: Install avahi for MDNS
      apt: pkg=avahi-daemon
      become: yes

    - name: Install ntpdate for time synchronisation
      apt: pkg=ntpdate
      become: yes
