---
- hosts: all

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes
      become: yes

    - name: Install avahi for MDNS
      apt: pkg=avahi-daemon
      become: yes

    - name: Install ntpdate for time synchronisation
      apt: pkg=ntpdate
      become: yes

    - name: Install pip
      apt: pkg=python-pip
      become: yes

    - name: Install docker-py
      pip: name=docker-py
      become: yes

  roles:
    - docker

  post_tasks:
    - name: Add vagrant user to user groups
      user: name=vagrant groups=docker append=yes
      become: yes

    - name: Juice Shop
      docker:
        name: juice-shop
        image: bkimminich/juice-shop
        ports:
          - "3000:3000"
        restart_policy: always
      become: yes
