---
- hosts: all

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes
      become: yes

    - name: Install avahi for MDNS
      apt: pkg=avahi-daemon
      become: yes

    - name: Install avahi-utils for working with MDNS
      apt: pkg=avahi-utils
      become: yes

    - name: Install ntpdate for time synchronisation
      apt: pkg=ntpdate
      become: yes

    - name: Install unzip
      apt: pkg=unzip
      become: yes

    - name: Install time
      apt: pkg=time
      become: yes

    - name: Install lynx command line web browser
      apt: pkg=lynx
      become: yes

  roles:
    - arachni
    - htcap
    - slowhttptest
    - wapiti
    - dnsmap
    - dnsrecon
    - scrapy
    - skipfish
    - nmap
    - ncrack
    - hping3
    - apache-bench
    - dig
    - mz
    - mitmproxy

  post_tasks:
    - name: Setup DNS nameserver
      lineinfile: path=/etc/resolv.conf line="nameserver 10.6.6.7" regex="nameserver.*"
      become: yes

    - name: Add resolv.conf update to .bashrc
      lineinfile: dest=~/.bashrc line="sudo sed -i 's/nameserver.*/nameserver 10.6.6.7/g' /etc/resolv.conf"
