---
- hosts: all

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes
      become: yes

    - name: Install avahi for MDNS
      apt: pkg=avahi-daemon
      become: yes

    - name: Install ntpdate for time synchronisation
      apt: pkg=ntpdate
      become: yes

    - name: Install pip
      apt: pkg=python-pip
      become: yes

    - name: Install docker-py
      pip: name=docker-py
      become: yes

  roles:
    - docker

  post_tasks:
    - name: Add vagrant user to user groups
      user: name=vagrant groups=docker append=yes
      become: yes

    - name: Create dnsmasq configuration
      copy:
        dest: /opt/dnsmasq.conf
        content: |
          log-queries
          no-resolv
          server=1.0.0.1
          server=1.1.1.1
          strict-order
          server=/security/10.6.6.7
          address=/tooling.security/10.6.6.6
          address=/victim.security/10.6.6.7
      become: yes

    - name: dnsmasq
      docker_container:
        name: dnsmasq
        image: jpillora/dnsmasq
        ports:
          - 8080:8080
          - 53:53/udp
        env:
          HTTP_USER: "admin"
          HTTP_PASS: "admin123"
        volumes:
          - /opt/dnsmasq.conf:/etc/dnsmasq.conf
        restart_policy: always
      become: yes

    - name: Juice Shop
      docker_container:
        name: juice-shop
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
        restart_policy: always
      become: yes

    - name: webgoat
      docker_container:
        name: webgoat
        image: webgoat/webgoat-8.0
        ports:
          - 3001:8080
        restart_policy: always
      become: yes

    - name: hackazon
      docker_container:
        name: hackazon
        image: ianwijaya/hackazon
        ports:
          - 3002:80
          - 3003:443
        restart_policy: always
      become: yes

    - name: adamdoupe/wackopicko
      docker_container:
        name: wackopicko
        image: adamdoupe/wackopicko
        ports:
          - 3004:80
        restart_policy: always
      become: yes

    - name: dvwa
      docker_container:
        name: dvwa
        image: vulnerables/web-dvwa
        ports:
          - 3005:80
        restart_policy: always
      become: yes
