- name: Clone SpiderFoot repository
  ansible.builtin.git:
    repo: "https://github.com/smicallef/spiderfoot.git"
    dest: "/opt/spiderfoot"
    version: master
    force: true
  become: true

- name: Create Python virtual environment
  ansible.builtin.command: python3 -m venv /opt/spiderfoot/venv
  args:
    creates: "/opt/spiderfoot/venv/bin/activate"
  become: true
  changed_when: false

- name: Upgrade pip in virtual environment
  ansible.builtin.command: "/opt/spiderfoot/venv/bin/pip install --upgrade pip"
  become: true
  changed_when: false
  register: pip_upgrade
  failed_when: pip_upgrade.rc != 0

- name: Install SpiderFoot requirements
  ansible.builtin.command: "/opt/spiderfoot/venv/bin/pip install -r /opt/spiderfoot/requirements.txt"
  args:
    chdir: "/opt/spiderfoot"
  become: true
  changed_when: false
  register: pip_install
  failed_when: pip_install.rc != 0

- name: Create a SpiderFoot launcher script
  ansible.builtin.copy:
    dest: /usr/local/bin/spiderfoot
    mode: '0755'
    content: |
      #!/bin/bash
      cd /opt/spiderfoot
      exec /opt/spiderfoot/venv/bin/python3 sf.py "$@"
  become: true
